const weather_icons = [
    { code: 1000, icon: 'images/sunny_sun.ico' },
    { code: 1003, icon: 'images/sunny_cloud.ico' },
    { code: 1006, icon: 'images/cloudy_cloud.ico' }, 
    { code: 1009, icon: 'images/cloudy_cloud.ico' },
    { code: 1012, icon: 'images/snowy_cloud.ico' },
    { code: 1117, icon: 'images/blizzard_cloud.ico' },
    { code: 1198, icon: 'images/tunder_cloud.ico' },
    { code: 1183, icon: 'images/light_rain.ico' },
    { code: 1024, icon: 'images/tunder_cloud.ico' },
    { code: 1063, icon: 'images/rainy_cloud.ico' },       
    { code: 1066, icon: 'images/rainy_cloud.ico' },        
    { code: 1069, icon: 'images/rainy_cloud.ico' },        
    { code: 1072, icon: 'images/rainy_cloud.ico' },         
    { code: 1087, icon: 'images/tunder_cloud.ico' },       
    { code: 1114, icon: 'images/snowflake.ico' },         
    { code: 1117, icon: 'images/blizzard_cloud.ico' },     
    { code: 1135, icon: 'images/fog.ico' },      
    { code: 1147, icon: 'images/fog.ico' },       
    { code: 1150, icon: 'images/rainy_cloud.ico' },       
    { code: 1153, icon: 'images/rainy_cloud.ico' },       
    { code: 1168, icon: 'images/light_rain.ico' },       
    { code: 1171, icon: 'images/light_rain.ico' },       
    { code: 1180, icon: 'images/light_rain.ico' },       
    { code: 1186, icon: 'images/rainy_cloud.ico' },       
    { code: 1189, icon: 'images/rainy_cloud.ico' },       
    { code: 1192, icon: 'images/rainy_cloud.ico' },       
    { code: 1195, icon: 'images/rainy_cloud.ico' },       
    { code: 1198, icon: 'images/tunder_cloud.ico' },       
    { code: 1201, icon: 'images/light_sleet.ico' },       
    { code: 1204, icon: 'images/snowy_cloud.ico' },        
    { code: 1207, icon: 'images/snowy_cloud.ico' },         
    { code: 1210, icon: 'images/snowy_cloud.ico' },       
    { code: 1213, icon: 'images/snowy_cloud.ico' },         
    { code: 1216, icon: 'images/snowflake.ico' },         
    { code: 1240, icon: 'images/rainy_cloud.ico' },         
    { code: 1030, icon: 'images/mist1.ico' },         
   
    { code: 'default', icon: 'images/404.png' }
  ];
  const weather_conditions_german = {
    'Sunny': 'Sonnig',
    'Partly Cloudy': 'Teilweise bewölkt',
    'Cloudy': 'Bewölkt',
    'Rainy': 'Regnerisch',
    'Snowy': 'Schneeregen',
    'Blizzard': 'Schneesturm',
    'Thunderstorm': 'Gewitter',
    'Light rain': 'Leichter Regen',
    'Light sleet': 'Leichter Schneeregen',
    'Fog': 'Nebel',
    'Light drizzle': 'Leichter Nieselregen',
    'Patchy snow possible': 'Möglicherweise vereinzelter Schnee',
    'Blowing snow': 'Schneetreiben',
    'Freezing fog': 'Eisiger Nebel',
    'Freezing drizzle': 'Eisiger Nieselregen',
    'Snow showers': 'Schneeschauer',
    'Heavy snow': 'Starker Schneefall',
    'Sleet': 'Schneeregen',
    'Ice pellets': 'Eiskörner',
    'Hail': 'Hagel',
    'Patchy rain nearby': 'Teilweise Regen',
    'Clear': 'Klar',
    'Overcast': 'Überwiegend bewölkt',
    'Thundery outbreaks in nearby': 'Gewitter in der Nähe',
    'Smoke': 'Rauch',
    'Haze': 'Dunst',
    'Dust': 'Staub',
    'Freezing rain': 'Eisregen',
    'Tornado': 'Tornado',
    'Squalls': 'Böen',
    'Funnel cloud': 'Trichterwolke',
    'Sandstorm': 'Sandsturm',
    'Dust storm': 'Staubsturm',
    'Widespread dust': 'Weitverbreiteter Staub',
    'Volcanic ash': 'Vulkanasche',
    'Widespread smoke': 'Weitverbreiteter Rauch',
    'Widespread haze': 'Weitverbreiteter Dunst',
    'Widespread fog': 'Weitverbreiteter Nebel',
    'Shallow fog': 'Flacher Nebel',
    'Partial fog': 'Teilweiser Nebel',
    'Patches of fog': 'Nebelfelder',
    'Freezing spray': 'Gefrierende Gischt',
    'Low drifting snow': 'Treibender Schnee',
    'Blowing snow mist': 'Schneetreiben',
    'Drizzle': 'Nieselregen',
    'Freezing drizzle': 'Gefrierender Nieselregen',
    'Heavy freezing drizzle': 'Starker gefrierender Nieselregen',
    'Light freezing rain': 'Leichter Eisregen',
    'Heavy freezing rain': 'Starker Eisregen',
    'Light rain shower': 'Leichte Regenschauer',
    'Heavy rain shower': 'Starke Regenschauer',
    'Squalls': 'Böen',
    'Thundery outbreaks': 'Gewitter',
    'Small hail': 'Kleiner Hagel',
    'Heavy hail': 'Starker Hagel',
    'Pellets': 'Eiskörner',
    'Glaze': 'Glatteis',
    'Thundery outbreaks possible': 'Mögliche Gewitter',
    'Blowing snow': 'Schneetreiben',
    'Blizzard': 'Schneesturm',
    'Windy': 'Windig',
    'Fair': 'Schön',
    'Cold': 'Kalt',
    'Hot': 'Heiß',
    'Isolated thunderstorms': 'Vereinzelte Gewitter',
    'Scattered thunderstorms': 'Vereinzelte Gewitter',
    'Widespread thunderstorms': 'Weitverbreitete Gewitter',
    'Chance of storm': 'Sturmgefahr',
    'Chance of rain': 'Regenwahrscheinlichkeit',
    'Chance of snow': 'Schneewahrscheinlichkeit',
    'Rain and snow': 'Regen und Schnee',
    'Sleet and snow': 'Schneeregen und Schnee',
    'Freezing rain and snow': 'Eisregen und Schnee',
    'Rain or snow': 'Regen oder Schnee',
    'Chance of rain or snow': 'Regen- oder Schneewahrscheinlichkeit',
    'Chance of sleet or snow': 'Schneeregen- oder Schneewahrscheinlichkeit',
    'Chance of freezing rain or snow': 'Eisregen- oder Schneewahrscheinlichkeit'
  };
  //array soll key von eglish und deutsch haben
  //get translation(methode)
  //lower methode usw